// Extracted verbatim from the supplied manuscript draft.
export const chapterOne = [
  "Silence. The first word I remember. The last, too. Memory speaks in it, thin, patient, unwilling to be interrupted. And yet the mornings in the Dolomites slip from me sometimes, as if they were never mine to keep.",
  "When they return, they come back in pieces: gold light on stone, frost on the inside of a pane, pine in the air like a held breath. We used to call it holy light. No one ever asked who lit it. No one was meant to.",
  "Here, in Scotland, there is rain against the glass and the small, dependable burn of whisky in my throat. That sound and that heat are real. They keep me in the room. Italy does not. Italy arrives like smoke, faint at first, then suddenly everywhere.",
  "I was eighteen when my mother signed me away to what they called a school for the gifted. A compound in the mountains, tucked beyond the roads that carried ordinary lives. She signed with a hand that did not tremble. I noticed that. I have noticed it for years. Some details do not soften.",
  "I tell myself I do not blame her. The sentence fits in the mouth the way prayer fits in a church: familiar, rehearsed, useful to those who want to keep walking. Some days it holds. Some days it doesn’t.",
  "The path began in cold, in quiet, beneath the bright emblem of the Sun.",
  "—",
  "January 1979. A northern winter. Frost clung to the inside of the car windows like brittle lace, turning the world beyond them into a pale blur. The Fiat was black and small and smelled faintly of petrol and damp wool. The heater worked only in moods. The driver did not speak.",
  "Milan thinned behind us: apartment blocks to towns, towns to villages, villages to bends in the road where the mountains began to rise, grey and enormous against the sky. The tyres hissed over wet gravel. The wipers dragged rhythm across the glass, opening brief clearings that closed again.",
  "My name stayed in my mouth like something hard.",
  "Luca Altomare.",
  "It carried more than a boy should have had to carry. In Milan, people said it quietly, as if the sound itself might stain them. Altomare. Blood tied to the old world, to the party, to what had fallen and yet did not stay buried. It had happened before I was born. That did not matter. Shame has no patience for chronology.",
  "My father, Emilio, had been imprisoned after the fall. Released, then gone. No note. No body. Only absence, which becomes its own kind of presence if you live with it long enough. Sometimes I tried to give that absence a shape I could endure: a secret he died for, a tragedy with clean edges. There was another possibility, harder and heavier. That he had simply walked away. Left the wreckage behind and did not look back.",
  "My mother grew smaller after that. Quieter. As if the house had narrowed around her.",
  "When the letter came, prestigious, official, neatly worded, she read it once and did not ask many questions. The school promised discipline, protection, excellence. It also promised no contact for years. That line was printed in plain ink. I remember her finger resting on it.",
  "She signed.",
  "—",
  "The gates looked newer than I expected. Refurbished stone. Crisp ironwork. Too clean for age, too cold for anything holy. The driver pulled up, killed the engine, and the silence that followed dropped heavily into the car.",
  "“We’ve arrived.”",
  "Three words. Flat.",
  "I stepped out. The air bit at once. It went through my coat as if the fabric were decorative. Snow compressed beneath my shoes with a muted crackle. My bag was small, as instructed. We had been told not to bring much. Everything would be provided.",
  "There was no welcoming committee. No teachers in sight. Only a man in a grey uniform standing near the gate, armed and unsmiling, with the posture of someone long accustomed to giving up his face in exchange for obedience.",
  "Before I really looked at him, I looked at the gun.",
  "Then the ironwork above him.",
  "A circle ringed by twelve sharp triangles, like teeth around an open mouth. The Sun. The same mark was stitched to his sleeve, faded by washing and wear.",
  "“Luca Altomare?” he asked.",
  "I nodded. My throat tightened. I shifted my bag higher on my shoulder, a useless adjustment, something to do with my hands.",
  "“Follow me.”",
  "He opened the gate. I glanced back once. The driver was already turning the car around.",
  "Then I stepped through.",
  "A stone path cut across a courtyard dusted with snow. Dormant flower beds. Trees stripped down to bone. I caught myself trying to imagine what the place might look like in summer, as if a different season could make a difference.",
  "Then the main entrance rose ahead of us: white stone, brass doors, a bell tower above it like a crown placed on the wrong head. Carved over the arch was the Sun again, watching from the stone itself.",
  "—",
  "Inside, the air changed. Stale radiator heat thickened it, carrying old varnish, wax, and the faint sweet trace of incense. The entry hall, later I learned they called it the Central Atrium, had high wooden ceilings and marble floors polished to a mirror. Light slid across the stone in long, careful bands.",
  "At the center of the floor, inlaid in gold, was the Sun.",
  "My foot angled around it before I had decided to move. A small refusal. My body knew first.",
  "The silence inside was different from the silence outside. Outside it belonged to winter. Here it felt arranged. Held in place. The building seemed to expect the same from us.",
  "For one brief, shameful moment, I wondered whether I had been sent somewhere beautiful.",
  "The thought passed quickly.",
  "—",
  "The guard led me across the hall and stopped at a side room. Beside the door stood a boy perfectly still. Nineteen, maybe twenty. He wore a white jacket with a high collar and a black sun stitched neatly over his chest. Two vertical black lines flanked the zipper. The cuffs matched. Everything about him was crisp, angular, severe.",
  "Then there were the shorts. High, pale, absurd in that mountain cold. The sight of bare thigh made my own skin ache.",
  "“Bag,” he said.",
  "No greeting. No name. His eyes moved over me with the brisk, impersonal attention of someone checking inventory.",
  "I handed it over.",
  "He set it on the table, unzipped it, and tipped it out. My clothes slumped into a loose pile. Underthings fell apart from the rest. He separated them with two fingers, examining each piece as though it might conceal something alive.",
  "When he found the dog-eared copy of Tex Willer, his mouth shifted.",
  "“These things are forbidden here, Lamb.”",
  "The word landed cleanly. No cruelty in it. No kindness either. Only classification.",
  "I kept my face still and pressed my tongue hard against a back tooth while he turned the comic over in his hands.",
  "From a drawer beneath the table he took out two slim booklets stamped with the black Sun and laid them down with quiet care.",
  "The Pocket Guide of the Ordo Solis\n The Doctrine of the Lamb",
  "Then he opened the wardrobe behind him and removed a folded uniform, white like his own, trimmed in deep crimson.",
  "“Put it on,” he said. “Then go to the North Wing. The Temple. You won’t miss it.”",
  "He did not look away.",
  "I heard my voice come out smaller than I meant it to. “Is there somewhere I can change?”",
  "One eyebrow lifted. He gave a slight shrug and gestured toward a wooden bench against the wall.",
  "No curtain. No corner. Just the open room between us.",
  "I understood.",
  "—",
  "The uniform felt wrong on my skin, too clean, too stiff, as if it had not yet learned the shape of a body. A thin band of crimson edged the jacket and cuffs, making the white look harsher.",
  "The halls toward the North Wing grew colder as I walked. The light thinned. The silence changed again. It gathered itself around corners, listening.",
  "At the end of a corridor stood black wood double doors carved with curling sun motifs. The handles were burnished. Above them, in old Fraktur lettering:",
  "THE SUN TEMPLE",
  "I stopped.",
  "My palms had gone damp inside my sleeves.",
  "A student passed in a uniform trimmed in black. He barely looked at me.",
  "“Wait here,” he said. “You’ll be called.”",
  "Then he was gone.",
  "I sat on the bench beside the doors and opened the smaller booklet. The paper smelled of dust and incense. The cover was cream, the lettering black, the Sun emblem printed again and again until it stopped feeling decorative and became something closer to pressure.",
  "The opening line read:",
  "You were born into chaos. The Sun does not ask permission to rise.",
  "I kept reading because it gave my hands somewhere to go.",
  "There was a word for me: Lamb.\n A word for the student assigned over me: Vessel.\n And, lower on the page, a phrase set apart in plain type:",
  "To be Claimed.",
  "My grip tightened on the booklet. The page edge pressed into the pad of my thumb.",
  "The four Pillars were listed beneath it. Judge. Bishop. Banker. Philosopher.",
  "Somewhere down the corridor, a radiator clicked once. The sound was small and precise. I looked up at once, though nothing moved.",
  "Then the doors opened.",
  "—",
  "The command to enter was not loud. It did not need to be.",
  "My feet moved.",
  "Inside, the air was heavier, dense with incense, old smoke, and something metallic underneath. Darkness seemed settled into the room rather than cast there. At the front stood a black marble altar. Above it a brazier burned, slow and controlled, the flame disciplined into stillness.",
  "Stained glass enclosed the chamber. No saints. No angels. Only martyrs twisted in fire, their faces rendered as suns, their hands extended in a rigid glass judgment that left no room for blessing.",
  "Two figures stood behind the altar, half-shaped by firelight. Their black uniforms were perfectly pressed, their trim gold, their sun emblems bright against the cloth. Their caps shadowed their faces, but their attention filled the room long before their features did.",
  "My legs began to tremble. I curled my fingers once, hard, then let them go.",
  "One of them spoke.",
  "“Luca Altomare, son of Emilio and Beatrice Altomare. Is it you who stands before the Sun?”",
  "My tongue felt thick. “Yes.”",
  "“Come closer.”",
  "I obeyed. Each step sounded too loud in the chamber. The brazier’s heat brushed my face and left the rest of me untouched.",
  "Up close, their faces were pale and furrowed, sharpened by age and by something that had little to do with kindness. One of them did not speak. His eyes gave me nothing back. The other watched me with a hunger that had dressed itself as devotion.",
  "“You were called to the Ordo Solis by the respected Matteo Aldani,” he said.",
  "The name struck low and hard.",
  "For an instant the floor seemed to shift under me. My stomach dropped. My fingers opened at my sides before I caught them and closed them again.",
  "“From now on,” he continued, “you will address him as Pillar Philosopher. And me, as Pillar Bishop.”",
  "I nodded. It happened automatically, manners climbing out of me like a reflex.",
  "A memory flashed. An apartment in Milan. Curtains drawn against the afternoon. Tea cooling in cups. Matteo Aldani speaking softly with my father while I pushed a wooden plane across the floorboards. Polish in the air. Old fabric. My mother telling me to be quiet.",
  "“Are you listening, boy?”",
  "The Bishop’s voice cracked through the memory. My heart gave a hard, sick jolt. I nodded again, too quickly.",
  "A sound came from the Philosopher. Dry. Brief. Almost amused.",
  "The Bishop stepped closer. I saw the fine red veins in the whites of his eyes. His breath carried something sweet and sour, wine left too long in a glass. He lifted a hand and touched my cheek.",
  "Lightly.",
  "I flinched before I could stop it.",
  "“Are you sure I can’t claim him, Matteo?” the Bishop asked.",
  "He spoke with the calm of someone discussing ownership of a chair.",
  "The Philosopher moved then, slow and certain. Firelight reached his face and found almost nothing in it. No anger. No mercy. No expression I knew what to do with.",
  "“No, Francesco,” he said. “He is mine. You know that.”",
  "His gaze settled on me. Not on the uniform. Not on the body inside it. Somewhere further in.",
  "“He is my little experiment.”",
  "The Bishop made a small sound that might have been disappointment. Or amusement. Then he clapped twice.",
  "The noise cracked through the Temple and scattered into the marble.",
  "Behind the altar, another set of doors opened into darkness.",
  "—",
  "A boy stepped through.",
  "He moved with quiet certainty, unhurried, practiced, as if the room had repeated itself around him often enough to become familiar. He could not have been much older than me. Perhaps twenty. Yet there was something finished in the way he held himself, something shaped by long use.",
  "His uniform was white like the others, trimmed in blue.",
  "Vessel.",
  "The word rose at once from the booklet.",
  "The brazier light touched his face. Chestnut hair, slightly unruly, as though sleep still clung to it. Hazel eyes, clear and distant at once. They did not have the sealed look I had already begun to expect. Something in them still caught light.",
  "He did not look at me immediately. His gaze seemed to move through the chamber, past the stained glass, beyond the altar itself.",
  "When he reached my side, he stopped with his hands at his sides and bowed to the two Pillars, slow and exact.",
  "The Bishop turned to me.",
  "“On your knees, Luca Altomare.”",
  "My body resisted for a fraction of a second. Nothing visible, just a tightening behind the ribs, a stupid last instinct. I looked sideways, quick as breath.",
  "The boy looked at me then.",
  "Leandro.",
  "His face gave away almost nothing. But his eyes were alert in a way the others’ had not been, as if some small private part of him had survived behind the training. He tilted his head once. The gesture was slight, practiced, difficult to read. Warning, perhaps. Instruction.",
  "I knelt.",
  "Stone met bone. Cold climbed up through my legs.",
  "The Bishop’s belt hung at my eye level, leather and buckle made ceremonial by proximity alone. He let the silence lengthen before both hands came down onto my head, fingers spread across my scalp.",
  "The pressure of them sank into my skin.",
  "“From this point onward,” he said, slowly, “you shall be named Lucian Altomare.”",
  "Lucian.",
  "The syllables hovered in the air as if waiting for me to betray myself. My mouth dried at once. My tongue pressed against my teeth. Somewhere deep in me, something small tightened and held.",
  "“A Lamb, Lucian,” the Bishop said. “And this is your Vessel, Leandro. You will address him as Vessel Leandro.”",
  "He paused.",
  "“Your name is ash now.\n Let the Sun rename you.\n Let obedience cleanse you.\n Let your Vessel shape you.\n And may your shadow never again outrun the light.”",
  "Then he pulled my head back and pushed it forward again, dismissive and almost playful.",
  "When his hands left me, the place they had rested still burned.",
  "I kept my eyes lowered. The stone beneath my knees felt like the only thing in the room that would not shift.",
  "—",
  "The Pillars withdrew into the dark as if it had been waiting for them.",
  "I stayed where I was.",
  "In less than an hour, my body had already learned to wait for permission before it even considered standing. Cold seeped into my joints. My knees began to ache.",
  "Leandro spoke at last. Quietly. Almost as if he were speaking to himself.",
  "“You can get up now.”",
  "I stood. Pins and needles rushed through my legs. Questions crowded the back of my throat, Temple, doctrine, who, why, but none of them made it into the air. Speech already felt expensive.",
  "So I followed him.",
  "We moved through corridors lined with polished wood and cold stone. The air smelled faintly of wax and damp fabric drying too slowly. Tall windows admitted the January sun in precise rectangles. Beyond the glass, the mountains stood silver and still.",
  "The place was beautiful. That was part of its power.",
  "Leandro walked without hesitation. He had the fluency of someone whose bones had memorized the rules before the mind needed to. His footsteps made a particular sound on the stone. I found myself listening for it, matching mine to it when I could.",
  "Up a flight of stairs. Along another corridor bright with winter light. Then to a door he opened without ceremony.",
  "I followed him in.",
  "The room was spare and clean to the point of discomfort. Two beds. Two desks. Approved books arranged on a narrow shelf. Curtains drawn back to let in the cold. The window framed a slice of sky so blue it almost hurt to look at.",
  "My bag was already beside one of the beds. Neat. Waiting.",
  "I stopped in the doorway. My shoulders had locked without my noticing.",
  "Leandro turned then. His gaze rested on me with a kind of measured curiosity, as though he were trying to decide whether I was breakable or troublesome, and which would be worse.",
  "“Well,” he said, with a casualness that did not belong in that room, “make yourself at home, I guess.”",
  "The line was so out of place it unsettled me more than cruelty would have.",
  "He glanced at his watch. “This is your bed. Unpack what you’ve got. We’ll head to lunch soon.”",
  "I nodded.",
  "In another life I might have asked something. Made a joke. Tested the air just to hear whether I still existed inside it.",
  "Instead I moved toward the bed.",
  "Because I had been told.",
  "Because he had said it.",
  "And already, without my understanding how, his voice had begun to matter."
];
